module.exports = {
  MAX_FIRST_NAME_LENGTH: 400,
  MAX_LAST_NAME_LENGTH: 400,
  MAX_ASSIGNMENT_INSTRUCTIONS_LENGTH: 1000,
  MAX_CODE_SNIPPET_LENGTH: 40000,
  MAX_ASSIGNMENT_LONG_FORM_QUESTION_LENGTH: 1000,
  MAX_ASSIGNMENT_LONG_FORM_ANSWER_LENGTH: 1000,
  MAX_EMAIL_LENGTH: 400,
  MAX_ANNOTATION_NOTE_LENGTH: 1000,

  MAX_CODE_SNIPPET_LENGTH: 1000,
  MAX_CODE_SNIPPET_TITLE_LENGTH: 200
}
